### ISSUE TITLE
Cannot Register a new Instagram client

### ISSUE THREAD

**Issue by alastairhm** [mcqn/instagram-to-mastodon#4]
You can no longer register a new client on Instagram, is there another way to get the information required for the script to run?

```
UPDATE: Starting October 15, 2019, new client registration and permission review on Instagram API platform are discontinued in favor of the Instagram Basic Display API. 
```

**Comment by amcewen** [comment]
Have had a look at this, and it seems Instagram are cranking up their hostile-to-the-open-web attitude :-(

The `Instagram Basic Display API` will let you get an access code which would be valid for a whole hour.  After that, from what I can tell, you'd need to jump through the authorization process again, including bouncing into your Instagram account and clicking on the "Authorize" button.

There's an `Instagram Graph API` that has more access, but only to business or "creator" accounts, rather than normal accounts.

So the only way _might_ be to scrape your Instagram page on the web.  I don't know how many barriers they put in front of that, given that I'm already scraping pages to get a better photo, it's probably doable, but I'm more motivated to stop using Instagram than I am to work round their stupid barriers right now...

**Comment by alastairhm** [comment]
Yeah, its doesn't look like it would be easy to fix.
Trying to get webhooks from IFTTT working but having issues.
Maybe will have a look at PixelFeed again as a Instagram alternative.
Thanks for the response.
